# Initializing libraries

In [11]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.preprocessing import MinMaxScaler

# Preprocessing data

In [2]:
DataFrame = pd.read_csv('Handson_Data.csv')

In [3]:
DataFrame

Region   Age   Income Online Shopper
0   India  49.0  86400.0             No
1  Brazil  32.0  57600.0            Yes
2     USA  35.0  64800.0             No
3  Brazil  43.0  73200.0             No
4     USA  45.0      NaN            Yes
5   India  40.0  69600.0            Yes
6  Brazil   NaN  62400.0             No
7   India  53.0  94800.0            Yes
8     USA  55.0  99600.0             No
9   India  42.0  80400.0            Yes

# Handling missing data

In [4]:
df_i= DataFrame[['Age']] # cleaning Age
meanReplace = SimpleImputer(missing_values=np.nan, strategy='mean')
df_i =meanReplace.fit_transform(df_i)
df_i

array([[49.        ],
       [32.        ],
       [35.        ],
       [43.        ],
       [45.        ],
       [40.        ],
       [43.77777778],
       [53.        ],
       [55.        ],
       [42.        ]])

In [5]:
dfL=DataFrame[['Income']]
meanReplace = SimpleImputer(missing_values=np.nan, strategy='mean')
dfL =meanReplace.fit_transform(dfL)
dfL

array([[86400.        ],
       [57600.        ],
       [64800.        ],
       [73200.        ],
       [76533.33333333],
       [69600.        ],
       [62400.        ],
       [94800.        ],
       [99600.        ],
       [80400.        ]])

In [6]:
DataFrame[['Age']]=df_i
DataFrame[['Income']]=dfL
DataFrame

Region        Age        Income Online Shopper
0   India  49.000000  86400.000000             No
1  Brazil  32.000000  57600.000000            Yes
2     USA  35.000000  64800.000000             No
3  Brazil  43.000000  73200.000000             No
4     USA  45.000000  76533.333333            Yes
5   India  40.000000  69600.000000            Yes
6  Brazil  43.777778  62400.000000             No
7   India  53.000000  94800.000000            Yes
8     USA  55.000000  99600.000000             No
9   India  42.000000  80400.000000            Yes

# Data Transformation
## Discretization

In [7]:
est = KBinsDiscretizer(n_bins=3, strategy='uniform', encode='ordinal')
df_i1 = est.fit_transform(df_i)
df_i1

array([[2.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [2.],
       [2.],
       [1.]])

In [15]:
est = KBinsDiscretizer(n_bins=3, strategy='uniform', encode='ordinal')
dfL1 = est.fit_transform(dfL)
dfL1

array([[2.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [2.],
       [2.],
       [1.]])

## MinMax

In [16]:
#df_S=DataFrame[['Region','Online Shopper']]
normalizer = MinMaxScaler(feature_range=(0,1))
norm_data = normalizer.fit_transform(df_i)
norm_data

array([[0.73913043],
       [0.        ],
       [0.13043478],
       [0.47826087],
       [0.56521739],
       [0.34782609],
       [0.51207729],
       [0.91304348],
       [1.        ],
       [0.43478261]])

In [17]:
normalizer = MinMaxScaler(feature_range=(0,1))
norm_data1 = normalizer.fit_transform(dfL)
norm_data1

array([[0.68571429],
       [0.        ],
       [0.17142857],
       [0.37142857],
       [0.45079365],
       [0.28571429],
       [0.11428571],
       [0.88571429],
       [1.        ],
       [0.54285714]])

In [18]:
DataFrame[['Age']]= norm_data
DataFrame[['Income']]=norm_data1
DataFrame

Region       Age    Income Online Shopper
0   India  0.739130  0.685714             No
1  Brazil  0.000000  0.000000            Yes
2     USA  0.130435  0.171429             No
3  Brazil  0.478261  0.371429             No
4     USA  0.565217  0.450794            Yes
5   India  0.347826  0.285714            Yes
6  Brazil  0.512077  0.114286             No
7   India  0.913043  0.885714            Yes
8     USA  1.000000  1.000000             No
9   India  0.434783  0.542857            Yes